#FROM registry.cn-hangzhou.aliyuncs.com/yintai/gcr:base-debian12-nonroot
FROM gcr.io/distroless/base-debian12:nonroot
# 设置工作目录
WORKDIR /app

# 设置启动点
ENTRYPOINT ["./app"]

# 复制应用
COPY /target/asset-harmony app